### ISSUE TITLE
Add 'Search with arabic/urdu keyboard ' from Qur'an.

### ISSUE THREAD

**Issue by Jejd222342** [AlfaazPlus/QuranApp#386] opened 2023-09-04 08:18 UTC
### Describe your suggested feature

Please, Dev. Add a feature in which i can search the whole of Quran with an Arabic/urdu keyboard. Like if i have to find ayat ul kursi, i should be able to find it by writing " آیت ال کرسی" . This feature will really make the app more appealing and helpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.

**Comment by faisalcodes** [comment] 2023-09-04 08:37
Duplicate of #361

**Closed** 2023-09-04 08:37 UTC
Labels: enhancement
