### ISSUE TITLE
[Verse Report]: 

### ISSUE THREAD

**Issue by Waa11a** [AlfaazPlus/QuranApp#249] opened 2023-04-22 14:50 UTC
### Describe the issue

Uthmani hafs script have misnumbered verses

### Screenshot

![IMG_20230422_163807](https://user-images.githubusercontent.com/89239945/233791465-ad1e2b4a-5e74-4533-88e7-fb7589778da4.jpg)
![Screenshot_20230422_164406](https://user-images.githubusercontent.com/89239945/233791528-5e3ad505-77ef-42e8-93a6-813d1a07c15c.jpg)

### Chapter and verse numbers

this is just an example if you open any surah you'll find them. it's almost the entire book

### QuranApp version

version 2023.04.21.1

**Comment by faisalcodes** [comment] 2023-04-22 14:53
Duplicate of #210

**Closed** 2023-04-22 14:53 UTC
Labels: verse report
