### ISSUE TITLE
Sakta issue on zoom

### ISSUE THREAD

**Issue by Mahad60** [AlfaazPlus/QuranApp#204] opened 2023-04-10 23:44 UTC
### Describe the issue

I had translation on with a bit of zoom. Now the sakta and the next word seems to be mixed. I am using Samsung Galaxy note 8 exynos variant and on 720p resolution power saving mode

### Screenshot

![Screenshot_20230411-043734_QuranApp](https://user-images.githubusercontent.com/57263949/231019796-b3af4066-ab2a-4f4d-a35c-6b6e798481be.jpg)

### Chapter and verse numbers

Chapter 3 verse 3

### QuranApp version

2023.04.02.1

**Comment by faisalcodes** [comment] 2023-04-11 04:05
I am unable to get what's the issue. Can you elaborate further?

**Comment by faisalcodes** [comment] 2023-04-11 13:11
It seems like a duplicate of #183 which is fixed in #201. The changes will reflect in the next release.

**Closed** 2023-04-11 13:11 UTC
Labels: verse report
