### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by Ab-Mr** [AlfaazPlus/QuranApp#422] opened 2024-01-14 14:45 UTC
### Steps to reproduce

```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10750)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2209)
	at android.view.View.requestLayout(View.java:27055)
	at android.view.View.requestLayout(View.java:27055)
	at android.view.View.requestLayout(View.java:27055)
	at android.view.View.requestLayout(View.java:27055)
	at android.view.View.requestLayout(View.java:27055)
	at android.view.View.requestLayout(View.java:27055)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(SourceFile:4)
	at android.view.View.requestLayout(View.java:27055)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
	at android.view.View.requestLayout(View.java:27055)
	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
	at android.view.View.setFlags(View.java:17525)
	at android.view.View.setVisibility(View.java:12466)
	at com.quranapp.android.activities.ActivityTafsir.a0(SourceFile:12)
	at a5.p0.i(SourceFile:273)
	at a9.a.j(SourceFile:9)
	at p9.d0.run(SourceFile:103)
	at kotlinx.coroutines.internal.d.run(SourceFile:12)
	at kotlinx.coroutines.scheduling.i.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
	Suppressed: p9.b0: [g1{Cancelling}@73d6b31, Dispatchers.IO]
```

### Expected behavior

none

### Actual behavior

I wanted to explain **آية**, then I activated Airplane mode, so with this problem
 **شرح ابن كثير**

### QuranApp version

2023.09.17.1

### Android version

Android 11

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.

**Comment by faisalcodes** [comment] 2024-01-15 05:07
Thanks, I'll look into it.

**Comment by faisalcodes** [comment] 2024-01-18 20:22
Can you tell me when does this happen? Steps to reproduce?

**Comment by Ab-Mr** [comment] 2024-01-22 18:39
I think, when the airplane mode was activated and before that the mobile data was active, the problem occurred

**Comment by faisalcodes** [comment] 2024-01-23 08:51
Closing because it is not clear.

**Closed by faisalcodes** 2024-01-23 08:51 UTC
Labels: bug
